---

- name: Set default facts
  set_fact:
    kvm_hugepages: 0

- name: Check wether HugePages are allocated or not
  when: huge_pages > 0
  set_fact:
    kvm_hugepages: 1

- name: Enable kernel hugepages
  become: yes
  template:
    src: templates/90-hugepages.conf
    dest: /etc/sysctl.d
    owner: root
    mode: 0644
 
- name: Apply sysctl options
  become: yes
  command: /sbin/sysctl -p --system

- name: Enable KVM Hugepages
  become: yes
  lineinfile:
    dest: /etc/default/qemu-kvm
    regexp: ^KVM_HUGEPAGES
    line: "KVM_HUGEPAGES={{ kvm_hugepages }}"
  register: hugepages

- name: Restart libvirt service if Hugepages modified
  become: yes
  when: hugepages.changed
  service:
    name: libvirt-bin
    state: restarted

