---

- include: packages.yml
  tags:
    - packages

- include: swap.yml
  tags:
    - swap

- include: hugepages.yml
  tags:
    - hugepages

- include: lvm.yml
  when: crypt_device is defined
  tags:
    - lvm
