---

- name: Update cache
  become: yes
  apt:
    update_cache: yes

- name: Install kvm
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: no
    state: present
  with_items:
    - python-libvirt
    - libvirt-bin
    - libvirt-dev
    - qemu-kvm
