---

- name: Create swap file
  become: yes
  command: dd if=/dev/zero of={{ swap_path }} bs=1M count={{ swap_megas }}
  args:
    creates: "{{ swap_path }}"

- name: Change swap file permissions
  become: yes
  file:
    path: "{{ swap_path }}"
    owner: root
    group: root
    mode: 0600

- name: Check swap file type
  command: "file {{ swap_path }}"
  register: swapfile

- name: Make swap file
  become: yes
  command: "mkswap {{ swap_path }}"
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  become: yes
  mount:
    name: none
    src: "{{ swap_path }}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present

- name: Mount swap
  become: yes
  command: "swapon {{ swap_path }}"
  when: ansible_swaptotal_mb < 1

