---

# Already updated by kvm dependency
#- name: Update cache
#  become: yes
#  apt:
#    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: no
    state: present
  with_items:
    # X2go server, es una solucion con menos latencia que Guacamole + VNC.
    - lxde
    - lxdm
    - x2goserver
    - x2goserver-xsession
    # GNS3
    - dynamips
    - vpcs
    - gns3

- name: Add ansible user to libvirtd group
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: libvirtd
    append: true

