---

# Already updated by kvm depemndency
#- name: Update cache
#  become: yes
#  apt:
#    update_cache: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: no
    state: present
  with_items:
    # Juniper vMX
    # See http://www.juniper.net/techpubs/en_US/vmx15.1/topics/reference/general/vmx-hw-sw-minimums.html
    - bridge-utils
    - qemu-kvm
    - libvirt-bin
    - python
    - python-netifaces
    - vnc4server
    - libyaml-dev
    - python-yaml
    - numactl
    - libparted0-dev
    - libpciaccess-dev
    - libnuma-dev
    - libyajl-dev
    - libxml2-dev
    - libglib2.0-dev
    - libnl-dev
    - python-pip
    - python-dev
    - libxml2-dev
    - libxslt-dev
    # vMX requiere vnc4server, no puedo usar mi combo favorito
    # xvfb + x11vnc... lo que si uso es lxde y su display manager lxdm
    - lxde
    - lxdm
    # X2go server, es una solucion con menos latencia que Guacamole.
    - x2goserver
    - x2goserver-xsession

- name: Add ansible user to libvirtd group
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: libvirtd
    append: true

