---

- name: Create vMX directory
  become: yes
  file:
    dest: /opt/vmx
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
    state: directory

- name: Unpack vMX package
  unarchive:
    copy: yes
    src: files/vmx-{{ vmx_version }}.tgz
    dest: /opt/vmx
    creates: /opt/vmx/vmx-{{ vmx_version }}/

- name: Remove original config samples
  file:
    dest: "/opt/vmx/vmx-{{ vmx_version }}/config/{{ item }}"
    state: absent
  with_items:
    - vmx.conf
    - vmx-junosdev.conf

- name: Add vMX instances configuration
  template:
    src: templates/vmx.conf
    dest: "/opt/vmx/vmx-{{ vmx_version }}/config/vmx-{{ item.name }}.conf"
    mode: 0644
  with_items: vmx_instances

- name: Add vMX links
  template:
    src: templates/vmx-junosdev.conf
    dest: "/opt/vmx/vmx-{{ vmx_version }}/config/vmx-junosdev.conf"
    mode: 0644

# Prefiero instalarlos manualmente, porque tardan un web...
#- name: Launch vMX instances
#  become: yes
#  command: ./vmx.sh -lv --install --cfg config/vmx-{{ item.name }}.conf
#  args:
#    chdir: "/opt/vmx/vmx-{{ vmx_version }}"
#    creates: "/opt/vmx/vmx-{{ vmx_version }}/build/{{ item.name }}"
#  with_items: vmx_instances

