---

- name: Load public keys
  set_fact:
    authorized_keys: "{{ lookup('file', '~/.ssh/authorized_keys') }}"

- name: Add public keys to authorized_keys
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    line: "{{ item }}"
    regexp: "^{{ item | regex_escape() }}"
  with_items: "{{ authorized_keys.splitlines() }}"
