---

# Already updated by KVM role
#- name: Update cache
#  become: yes
#  apt:
#    update_cache: yes

- name: Install host dependencies
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: no
    state: present
  with_items:
    # vMX
    - linux-firmware
    - cpu-checker
    - python-netifaces
    - python-jinja2
    # Vagrant KVM
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - zlib1g-dev
