---

- name: Add .vimrc config file
  copy:
    src: files/vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0644

- name: Download Vagrant
  get_url:
    dest: "{{ ansible_env.HOME }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    force: no
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"

- name: Install Vagrant
  become: yes
  apt:
    deb: "{{ ansible_env.HOME }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    state: present
    update_cache: no

- name: Install Vagrant KVM plugins
  command: vagrant plugin install "{{ item }}"
  with_items:
    - vagrant-libvirt
    - vagrant-mutate

- name: Download required boxes
  command: "vagrant box add {{ item }}"
  ignore_errors: true
  with_items: vagrant_boxes

- name: Mutate downloaded boxes to libvirt
  command: "vagrant mutate {{ item }} libvirt"
  ignore_errors: true
  with_items: vagrant_boxes

