---

# Si estamos cifrando, montar /var/lib/docker en un volumen
- name: Check docker LVM
  become: yes
  when: (crypt_device is defined) and (docker_lvm_size is defined)
  lvol:
    lv: docker
    size: "{{ docker_lvm_size }}"
    state: present
    vg: tank

- name: Check LVM filesystem
  become: yes
  when: (crypt_device is defined) and (docker_lvm_size is defined)
  filesystem:
    dev: /dev/mapper/tank-docker
    fstype: ext4

- name: Check docker mountpoint exists
  become: yes
  when: (crypt_device is defined) and (docker_lvm_size is defined)
  file:
    dest: /var/lib/docker
    state: directory
    mode: 0755

- name: Mount filesystem to /var/lib/docker
  become: yes
  when: (crypt_device is defined) and (docker_lvm_size is defined)
  mount:
    name: /var/lib/docker
    src:  /dev/mapper/tank-docker
    opts: defaults,noauto
    passno: "0"
    dump:   "0"
    state: mounted
    fstype: ext4

- name: Add docker apt key
  become: yes
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    state: present
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker apt repository from trusty
  become: yes
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    update_cache: no
    name: "{{ item }}"
  with_items:
    - docker-engine

- name: Install docker python packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-py

- name: Add vagrant user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

# Usamos la red de gestion que hemos definido en el rol "vagrant"
- name: Make docker use existing libvirt bridge
  become: yes
  lineinfile:
    dest: "/etc/default/docker"
    line: DOCKER_OPTS="-b=virbr100"
    regexp: ^DOCKER_OPTS
  notify: Restart docker

# Hacer el servicio activo por defecto, si no estamos cifrando
- name: Start docker service
  become: yes
  service:
    name: docker
    enabled: no
    state: started

# Hacer el servicio persistente al arranque, si no esta,os cifrando
- name: Make docker service enabled on boot
  when: crypt_device is not defined
  become: yes
  service:
    name: docker
    enabled: yes
