Vagrant.configure("2") do |config|

  # Tell Vagrant where would you like to start your VMs (you can also have a
  # specific per-VM configuration. Do not put this section in case you want to
  # start your VMs on the same host)
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.nested = true
  end

  # Let's provision it by running a script. You can also run
  # puppet, chef, ansible, and others. Check the Vagrant website for
  # details.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../playbooks/olive.yml"
    ansible.groups = {
      "olive" => ["olive"]
    }
  end

  # Machines are Ubuntu 14.04 boxes
  config.vm.box = "ubuntu/trusty64"

  # Here's our VM configuration
  config.vm.define "olive" do |machine|

    # Set memory and number of CPUs
    machine.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.cpus = 4
    end

    # Hostname
    machine.vm.box = "ubuntu/trusty64"
    machine.vm.hostname = "olive"

    # Create dedicated mgmt network for vMX instances, and link it
    # to dedicated bridge 'vMX_mgmt'
    machine.vm.network :private_network, ip: "192.168.199.20",
      :mac => "0A:00:DD:00:01:20",
      :libvirt__adapter => 1,
      :libvirt__network_name => 'vMX_mgmt'
     
    # Forward port 3389 to port 22 in the VM
    machine.vm.network "forwarded_port", guest: 22, host: 3389,
      protocol: 'tcp', gateway_ports: true, host_ip: '*'

  end

end
