---

# Version de VMX descargada
vmx_version:  "14.1R6.4"
vfpc_version: "20151026"

# Instancias VMX
vmx_instances:

  - name: v11
    vcp_port: 8611
    vfp_port: 8711
    # Las direcciones de gestion tienen que pertenecer al rango de la
    # interfaz eth0 del equipo. El proveedor vagrant-libvirt enlaza esa
    # interfaz a una red particular **libvirt-vagrant** para la que usa
    # el direccionamiento 192.168.121.0/24 por defecto.
    vcp_ip: 192.168.121.101
    vfp_ip: 192.168.121.111
    # Utilizo el cuarto byte de las MACs como identificador del host
    vcp_mac: 0a:00:dd:11:ff:01
    vfp_mac: 0a:00:dd:11:ff:02
    interfaces:
      - 02:06:0a:11:00:00
      - 02:06:0a:11:00:01
    
  - name: v12
    vcp_port: 8612
    vfp_port: 8712
    vcp_ip: 192.168.121.102
    vfp_ip: 192.168.121.112
    vcp_mac: 0a:00:dd:12:ff:01
    vfp_mac: 0a:00:dd:12:ff:02
    interfaces:
      - 02:06:0a:12:00:00
      - 02:06:0a:12:00:01
 
vmx_links:
  # Los dos nodos, punto a punto por el puerto 0/0/1
  - endpoint_1:
      vm: v11
      device: ge-0/0/1
    endpoint_2:
      vm: v12
      device: ge-0/0/1

