---

- name: Provision GNS3 server
  hosts: gns3
  vars:
    swap_path: /swapfile
    swap_megas: 4096
    # Cuidadito con las huge_pages! el tamaño de memoria
    # asignado a huge_pages (huge_pages * 2MB) debe ser menor que
    # el total disponible. si no, el equipo no arranca porque
    # "init" se queda sin memoria.
    # Aqui contamos con que el equipo tiene 12 GB de RAM, y
    # reservamos para hugepages (4 * 1024MB)/2 = 2048 paginas.
    # De las dos maquinas virtuales del vMX (vcp y vfp), solo el forwarding
    # plane usa HugePages. Como cada maquina vfp la estoy configurando con
    # 1024 MB, con 4 gigas tengo ya para 2-3 maquinas, habra que valerse.
    huge_pages: 2048
    apt_repos:
      - ppa:x2go/stable
  roles:
    - kvm
    - gns3
