---

- hosts: routers

  tasks:

    - include: tasks/guest-packages.yml
      tags:
        - packages

    - include: tasks/hugepages.yml
      tags:
        - hugepages

    - include: tasks/guest-vmx.yml
      tags:
        - vmx

  handlers:

    - include: handlers/guest-main.yml
      tags: always
